# Generated by Django 5.1.3 on 2025-06-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_delete_blogmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/images",
                verbose_name="Изображение",
            ),
        ),
    ]
