# Generated by Django 4.2.2 on 2025-06-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="checkbox",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
